### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by jaanos** [zigakodric/Letalski-prevozniki#1]
Glede na to, da nisi predstavljal teme, bom kar tukaj pokomentiral ER diagram.

* Na ER diagramu se nikoli neposredno ne povežeta dve entiteti - vedno naj bo vmes relacija. Puščice gredo vedno v smeri relacije.
* Nisem prepričan, če razumem entiteto *Destinacija*. Smiselno bi bilo vsako destinacijo povezati z bližnjimi letališči (ne nujno samo z enim). Atributa *Prihod* in *Odhod* bi bolj ustrezala potovanju na samo destinacijo (teh bo seveda lahko tudi več za isto destinacijo). Prav tako ni jasno, kaj predstavlja *Sprememba*.
* Manjka entiteta *Letalska družba*, ki jo imaš zaenkrat samo kot atribute.
* Čeprav v praksi nekatere povezave imajo postanke, svetujem, da zaradi enostavnosti vsako povezavo obravnavaš brez postankov (tj., če ima povezava postanek, narediš dve povezavi). Povezava naj ima torej dve relaciji na letališče (odhodno, prihodno) in še relacijo na letalsko družbo. Tako vsi ti atributi niso potrebni.
* Vsak let pripada neki letalski povezavi - poleg tega je določen še s časom odhoda, tako da ga lahko predstaviš kot šibko entiteto. V vsakem primeru gre puščica iz leta, ne iz letalske povezave.
* Vsaka karta združuje enega ali več letov - tako ni potrebno imeti relacije z letalsko povezavo, saj je z njo povezana preko leta.

**Comment by zigakodric** [comment]
Se opravičujem za pozen odgovor, do danes sem bil namreč odstoten.  Mislim, da sem večino napak odpravil. Ne razumem pa, zakaj morajo biti letalske družbe lastna entiteta in kam naj jih umestim.

**Comment by jaanos** [comment]
Načeloma so letalske družbe nekaj oprijemljivega - zanje najbrž želiš hraniti kaj več kot samo ime (pa tudi če ne, se vedno lahko kasneje izkaže potreba). Tako imaš potem lahko relacijo med letalsko povezavo in letalsko družbo (tj., vsako povezavo izvaja neka družba) - če bi imel samo neko tekstovno polje, bi tam načeloma lahko bilo karkoli, tako bo pa morala obstajati referenca na obstoječo letalsko družbo. Pri posameznem letu je ne potrebuješ, saj je določena preko letalske povezave (vsak let pripada natanko eni povezavi, tako da bi morala puščica iti iz leta v relacijo - puščice so vedno v smeri relacije!).

Mimogrede, trenutno imaš eno relacijo med dvema letališčema in dvema letalskima povezavama. Če želiš podati začetno in končno letališče za letalsko povezavo, naredi dve relaciji - pri obeh bo puščica iz letalske povezave v relacijo (torej ena povezava ima natanko eno začetno in natanko eno končno letališče).

**Comment by zigakodric** [comment]
Baze bom zasnoval drugače, tako da bo naredil ER diagram na novo.
