### ISSUE TITLE
Manjša težava

### ISSUE THREAD

**Issue by zigakodric** [zigakodric/Letalski-prevozniki#2]
Imam manjšo težavo.  Pri aplikaciji si izberemo izhodno letališče. To izbiro potem uporabimo, da najdemo  možne destinacije. Vendar ne vem, kam si program "zapiše" našo izbiro oz. kako dostopati do nje.  V server.R  v 22 vrstici pride do te težave. Sedaj imam narejeno, kot da je izhodno letališče Ljubljana, želel pa bi da vrne tabelo glede na letališče, ki smo si ga izbrali.

**Comment by jaanos** [comment]
Najbolje bo, da izbirnik letališč nastaviš tako, da ti vrača ID-je letališč, prikazuje pa njihova imena:
```R
  uvoz_mesta <- reactive({
    t <- dbGetQuery(con, "SELECT  mesto, id from letalisca")
    setNames(t[[2]], t[[1]])
  })
```
Potem lahko do izbire dostopaš kot npr. `input$mesta`, kjer je ime polja enako ID-ju izbirnika (ali drugega vnosa):
```R
query <- sqlInterpolate(con, sql, id1 = input$mesta)
```

Mimogrede, da sem lahko pognal aplikacijo, sem moral v `server.R` dodati vrstici
```R
library(RPostgreSQL)
source("auth_public.R")
```
Prav tako sem moral odstraniti reference na neobstoječo spremenljivko `letalisca`.

Imam še sledeči pripombi:
* V `server.R` ustvariš pogled in ga nato pobrišeš. Tega ne počni - raje ustvari splošen pogled v sami bazi - torej brez pogoja `WHERE`, ki ga potem dodaš, ko uporabiš pogled.
* V `auth_public.R` imaš svoje geslo za dostop do baze, ki je tako za vekomaj objavljeno na internetu. Svetujem torej, da geslo zamenjaš, v `auth_public.R` pa naj bodo podatki za prijavo z uporabnikom `javnost` - treba bo seveda nastaviti ustrezne pravice (glej pdurcik/Baza-clanstva-RDR#3). Svoje geslo imaš seveda lahko v datoteki `auth.R` (zaradi vnosa v `.gitignore` je seveda ni na repozitoriju), ki je namenjena prijavi za ustvarjanje in polnjenje baze.

Svetujem še, da znotraj funkcije `server` (lahko kar takoj na začetek) dodaš še
```R
  session$onSessionEnded(function() {
    dbDisconnect(con)
  })
```
Tako se bo povezava na bazo ob izhodu iz aplikacije zaprla in tako ne bo težav s prevelikim številom odprtih povezav. V izogib napakam zaradi manjkajočih podatkov lahko uporabiš tudi funkciji `validate` in `need` - tako lahko na začetek `najdi_destinacije` (ki je sicer trenutno v kodi podvojen) dodaš npr.
```R
validate(need(input$mesta != '', "Izberi odhodno letališče"))
```

**Comment by zigakodric** [comment]
Najlepša hvala. Večino težav sem odpravil, ne razumem pa vašega komentarja glede ustvarjanja VIEWov. Torej če prav razumem ga direktno ustvarim npr. z ukazom dbsSendQuery,(con, "CREATE VIEW zacasno") že takoj v uvozu, potem pa v kodi server dostopam do njega in ga spreminjam? Ampak s katerim ukazom pa lahko v celoti spremenim že narejeni view?
Pojavlja se mi manjša težava.  Če pošljem ukaz dbSendQuery(con, "DELETE from letalske_povezave WHERE idprihodno = '\N'; ") iz R-a (Uvoz.R 54 vrstica) pride do napake, če pa direktno na bazi vpišem DELETE from letalske_povezave WHERE idprihodno = '\N' pa deluje brez problema.

**Comment by jaanos** [comment]
Pogled lahko ustvariš vnaprej (torej pri uvozu oziroma ustvarjanju baze), kasneje pa ga ne spreminjaš - z njim delaš tako kot z običajno tabelo. Pogoj WHERE , kot si ga imel v kodi, seveda v trenutku ustvarjanja pogleda ne bo znan, zato ga podaš pri poizvedbi, ki uporabi pogled. Ta seveda tudi ne bo začasen, zato bi bilo primernejše kako drugo ime.

Znak \ se v R-ovih nizih (podobno kot tudi v Pythonu in drugih programskih jezikih) uporablja v ubežnih zaporedjih za vstavljanje posebnih znakov. Če ga hočeš vključiti kot takega, ga podvoji.

**Comment by zigakodric** [comment]
Najlepša hvala. Težave sem odpravil in projekt po mojem mnenju zaključil.
